/*
 * Brandon Abbenhuis
 * brandon.abbenhuis@student.nhlstenden.com
 * Date: 3-4-2019
 * Description: Main class
 * Opdracht: 5
 * @version: 1.0
 */
package javaeindopdracht;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class JavaEindOpdracht {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {      
        SwingUtilities.invokeLater(() -> {
            JFrame window = new SchaatsKampioenschappen("Schaats Kampioenschappen");
            window.setSize(800, 450);
            window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            window.setVisible(true);
        });
    }

    /**
     * Custom function to round the big doubles generated by Rondetijd
     * manipulation.
     *
     * @param value The number to round
     * @param places The amount of decimals to round to
     * @return The rounded number
     */
    public static double round(double value, int places) {
        if (places < 0) {
            throw new IllegalArgumentException();
        }

        BigDecimal bd = new BigDecimal(value);
        bd = bd.setScale(places, RoundingMode.HALF_UP);
        return bd.doubleValue();
    }
}
